### ISSUE TITLE
6.4: Ensure your RPN calculator works with std::complex

### ISSUE THREAD

**Issue by rafaelkallis** [alpox/CPP-Exercises#5]

**Comment by rafaelkallis** [comment]
@alpox 
@PascalSiemon 
min function can only work if we make a custom *complex_number* class. In the task description, it states we should use std::complex, which doesn't have comparison operators except *==* and *!=*

**Comment by alpox** [comment]
@rafaelkallis as far as i know, one can define seperate operators for existing classes outside of the class scope. May be worth to try

**Comment by rafaelkallis** [comment]
@alpox not found a way to accomplish out of class scope operator declaration. 

~~Workaround found: will implement subclass of std::complex and declare operator there. Technically each subclass of std::complex is also std::complex. No restriction on inheritance on instructions listed, thus I will do it that way.~~

**Comment by alpox** [comment]
@rafaelkallis I added 2 possible traits for this task. 1 - i integrated the `<` operator for the complex class without any calculations (since i don't know what exactly you wanted to calculate)
2. I made a template specialization for mymin which throws an invalid_argument error on call with a complex number and catch this one during the call to provide an error message in the RPN calculator.

Both variants seem to be viable to me. You can choose one :-)
